### ISSUE TITLE
Support new PHP 8.2 syntaxes

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHP_CodeSniffer#105]
[PHP 8.2](https://www.php.net/releases/8.2/en.php) includes the following new syntaxes for which it should be verified if the Tokenizer needs updates and/or whether any sniffs need updates:

### To do
_All done_

### Done

- [Readonly classes](https://wiki.php.net/rfc/readonly_classes)
    - [x] Tokenizer changes needed - PR squizlabs/PHP_CodeSniffer#3773 / #34
    - [x] Updates needed to utility functions - `getClassProperties()` - PR squizlabs/PHP_CodeSniffer#3686
    - [x] Sniff updates needed - PRs squizlabs/PHP_CodeSniffer#3728, squizlabs/PHP_CodeSniffer#3816, squizlabs/PHP_CodeSniffer#3826
- Allow [`null`, `false`](https://wiki.php.net/rfc/null-false-standalone-types), [`true`](https://wiki.php.net/rfc/true-type) as stand-alone types
    - [x] Tokenizer changes needed - PR squizlabs/PHP_CodeSniffer#3662 / #49
    - [x] Updates needed to utility functions - `getMethodProperties()`, `getMethodParameters()`, `getMemberProperties()` - PR squizlabs/PHP_CodeSniffer#3662 / #49
    - [x] Sniff updates needed - PR squizlabs/PHP_CodeSniffer#3662 / #49
- [Constants in traits](https://wiki.php.net/rfc/constants_in_traits)
    - [x] ~~Tokenizer changes needed~~
    - [x] ~~Sniff updates needed~~
- [Disjunctive Normal Form Types](https://wiki.php.net/rfc/dnf_types)
    - [x] Tokenizer changes needed - see #387, PR #461
    - [x] Sniff updates needed - also see squizlabs/PHP_CodeSniffer#3731, PRs #471, #472, #473, #478
