### ISSUE TITLE
4.0 | Make sure that everything which was deprecated in 3.x has been removed in 4.0

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHP_CodeSniffer#6]
- [x] [1.4.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/1.4.0): `$ignoreComments` parameter for the `AbstractPatternSniff::__construct()` method. - PR #974
- [x] [3.2.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.2.0): Old-style ignore annotation syntax - PR #975
- [x] [3.3.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0): Old-style (comma-delimited string) setting of array properties - PR #976
- [x] [3.3.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0): T_ARRAY_HINT Token - PR #977
- [x] [3.3.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0): T_RETURN_TYPE Token - PR #977
- [x] [3.3.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.3.0): Squiz.WhiteSpace.LanguageConstructSpacing Sniff - PR #979
- [x] [3.4.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.4.0): Generic.Formatting.NoSpaceAfterCast Sniff - PR #980
- [x] [3.5.7](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.5.7): The new method of PHP 8.0 tokenizing for namespaced names has been reverted to the pre 8.0 method. This change will be removed in PHPCS 4.0 as the PHP 8.0 tokenizing method will be backported for pre 8.0 versions
- [x] [3.8.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0): The third parameter for the Ruleset::setSniffProperty() method has been changed to expect an array, Existing code will continue to work but will throw a deprecation error - PR #978 
- [x] [3.9.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.9.0): The complete MySource standard - #276 + squizlabs/PHP_CodeSniffer#2471  - PR #981
- [x] [3.9.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.9.0): JS/CSS support + all JS/CSS specific sniffs - #276 + squizlabs/PHP_CodeSniffer#2448
- [x] [3.9.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.9.0): ExactMatch::getBlacklist() and ExactMatch::getWhitelist() methods - see #198 and #199
- [x] [3.9.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.9.0): Zend.Debug.CodeAnalyzer - see #277 / #58
- [x] [3.12.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.12.0): The `print*()` methods in the `Generator` classes - See #755
- [x] [3.12.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.12.0): Support for sniffs not implementing the PHPCS `Sniff` interface - See #694
- [x] [3.12.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.12.0): Support for including sniffs which don't comply with the PHPCS naming conventions by referencing the sniff file directly - See #689
- [x] [3.12.0](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.12.0): The (partially) support for external standards named "Internal" - See #799
- [x] [3.12.1](https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.12.1): Generic.Functions.CallTimePassByReference- see #921

**Comment by jrfnl** [comment]
Loosely related to #120

**Comment by jrfnl** [comment]
All related PRs have been merged into the new 4.x branch. Closing this ticket as fixed.
