### ISSUE TITLE
4.0 | Formally stop support for sniffs not complying with the PHPCS naming conventions

### ISSUE THREAD

**Issue by jrfnl** [PHPCSStandards/PHP_CodeSniffer#689]
While PHPCS currently has partial/limited support for sniff file includes of sniffs which do not comply with the PHPCS naming conventions (as outlined in the [Coding Standard Tutorial](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial)), AFAICS this is more by accident than by design and I propose to formally drop support for this in PHPCS 4.0.

### What does "formally drop support" mean ?

- [x] Add a deprecation notice in the release notes of the next minor (soft deprecate). - done via #885
- [x] Add a runtime deprecation notice in one of the last pre-4.0 releases (hard deprecate). - PR #892
- [ ] A mention of this in the release notes/upgrade guide(s) for 4.0.
- [x] Revert PR #676 (remove leniency about sniffs not following naming conventions from the `Common::getSniffCode()` method) - PR #987
- [ ] If/when code is discovered which explicitly supports unconventional setups, remove that code (and any related tests; or possibly: change the tests to confirm this is _not_ supported).
    Note: this task does not have to be _completed_ for the 4.0 release and code covered by this task can be removed at any point in time _after_ the 4.0 release, as long as the 4.0 task 1 (explicit mention in release notes and upgrade guide) has been executed.
- [ ] No longer accept any bug reports/feature requests related to sniffs which do not comply with the PHPCS naming conventions and close those immediately and without hesitation.
- [x] Other than that, I think it would be good to review the text of the [Coding Standard Tutorial](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial) and to clarify the expected naming conventions where needed.

Note: including sniffs by file name will still be supported, but the sniffs included MUST be in a directory structure and with a namespace and class name which comply with the PHPCS naming conventions.

Related #675, #680, #683

### Opinions ?

/cc @asispts @dingo-d @fredden @GaryJones @greg0ire @kukulich @michalbundyra @Ocramius @sirbrillig @stronk7 @weierophinney @wimg

**Comment by greg0ire** [comment]
Does PHPCS have a deprecation mechanism that could be leveraged to make people aware of this in 3.x, and to migrate ahead of time? Maybe that could reduce the number of reports filed.

**Comment by dingo-d** [comment]
A deprecation notice would be great and would definitely urge the external standards maintainers to fix this ahead of time.

**Comment by jrfnl** [comment]
> Does PHPCS have a deprecation mechanism that could be leveraged to make people aware of this in 3.x, and to migrate ahead of time? Maybe that could reduce the number of reports filed.

Good point. PHPCS doesn't have a deprecation mechanism for this, but I think this can probably be detected when loading the ruleset, which would mean we could throw a deprecation notice without impacting CS runs.

I'm going to look into this.

**Comment by fredden** [comment]
Yes to the plan, but I'd also like to see a code change which detects sniffs which do not confirm and refuses to load these into a ruleset, with a user-visible notice ideally.

**Comment by greg0ire** [comment]
Sounds like a great improvement!

**Comment by mk-mxp** [comment]
We have been struggling to adjust our custom sniff to the naming conventions, as we use no full featured coding standard with an XML, but directly include the class in the main configuration. Our struggle was due to these points:

* The [Coding Standard Tutorial](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial) contains all the steps required to setup a full featured coding standard, but has no instructions on our use case
* The [Annotated Ruleset](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Annotated-Ruleset) only shows how to refer to the class file, but has no further details

I suggest the following changes to these places, now or when the naming conventions are enforced:

**[Annotated Ruleset](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Annotated-Ruleset)**

```
<!--
   If you are including sniffs that are not installed, you can
   reference the sniff class using an absolute or relative path
   instead of using the sniff code.
-->
```

should become

```
<!--
   If you are including sniffs that are not installed, you can
   reference the sniff class using an absolute or relative path
   instead of using the sniff code.
   The path and class name must follow the naming conventions
   outlined in the Coding Standard Tutorial. See
   https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial
-->
```

**[Coding Standard Tutorial](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/Coding-Standard-Tutorial)**

I suggest adding a heading `Naming conventions` that can be linked to directly. As far as I remember, the conventions are:

* Path structure `{any prefix}/{Coding standard name}/Sniffs/{Category}/{SniffName}Sniff.php`
* Namespace structure `{any prefix}\{Coding standard name}\Sniffs\{Category}\{SniffName}`
* Resulting sniff name `{Coding standard name}.{Category}.{SniffName}` to use in rulesets
* No `.`, `/` or `\` allowed in `{Coding standard name}`, `{Category}` and `{SniffName}`
* Choose any `{Coding standard name}`, `{Category}` and `{SniffName}` you like

Such a summarized specification of the naming convention would be enough, I think.

**Comment by jrfnl** [comment]
FYI: I'm nearly finished with all the work on the Ruleset class. Turned out that writing those tests was quite a lot of work 😉. 
Once PR #801 has been merged, I can pull the changes as outlined in my comment above https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/689#issuecomment-2482992507

So... I've now also spend some time on the wiki and have added a new page ["About Standards for PHP_CodeSniffer"](https://github.com/PHPCSStandards/PHP_CodeSniffer/wiki/About-Standards-for-PHP_CodeSniffer) which includes detailed information and examples about the naming conventions (and more).
Links to the new page have been added in the Annotated Ruleset and the Coding Standard Tutorial pages.

I'd love for you all to have a read through the new page. Feedback and improvements to the page are very welcome.

**Comment by greg0ire** [comment]
Very clear wiki page!

I think there are possibly some small fixes:

build-in => built-in
end on => end with

I'm not familiar with wiki pages, but if it's the same as for regular markdown file, I'd enable syntactic coloration with the syntax that consists in following the triple backticks with `php`

Also, I don't think invalid examples are useful given how clear the rest of the pages already is, they could even be confusing if somebody reads too fast and decides to use copy/paste from the wrong section.

**Comment by mk-mxp** [comment]
Very impressive piece of documentation! And the Annotated Ruleset got a link to the naming conventions, too. Thanks a lot for your work!

I also like the invalid examples and don't think they do any harm. There is lots of valid copy&paste sources directly above those. Often it's easier to see your own faulty decisions in a negative example compared to mentally diffing against valid code.

**Comment by jrfnl** [comment]
@greg0ire @mk-mxp Thank you both for reviewing and for your feedback.

I've made the following updates to the page now:
* Syntax highlighting for the PHP code samples (not sure how I missed that the first time around, sorry about that)
* Spelling/grammar fixes as suggested by @greg0ire
* I've kept the invalid examples for now, but have added a ❌ in front of the description for each, which should hopefully lessen the chance that people copy an invalid code sample.

**Comment by jrfnl** [comment]
Made one more update to the page:

> The name "Sniffs" MUST NOT be used as a category name.

**Comment by jrfnl** [comment]
The changes outlined in comment https://github.com/PHPCSStandards/PHP_CodeSniffer/issues/689#issuecomment-2482992507 have (finally) been pulled...: https://github.com/PHPCSStandards/PHP_CodeSniffer/pull/857

I'd really appreciate a critical look at that PR and welcome reviews.

**Comment by jrfnl** [comment]
FYI: PR #892 is now open to add the deprecation notice.
